import {Component} from '@angular/core';
import {MaterialModule} from "../../material.module";
import {TablerIconsModule} from "angular-tabler-icons";
import {CommonModule} from "@angular/common";

@Component({
  selector: 'app-available-workers',
  standalone: true,
  imports: [MaterialModule, TablerIconsModule, CommonModule],
  templateUrl: './available-workers.component.html',
  styleUrl: './available-workers.component.scss'
})
export class AvailableWorkersComponent {
  public userCards = [
    {
      id: 1,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Johnathan Doe',
      profession: 'Driver',
      address: '795 Folsom Ave, NY, 10003',
      phone: '(123) 456-7890',
    },
    {
      id: 2,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'George Johnson',
      profession: 'Errand Runner',
      address: '36 W 138th St,  NY, 10037',
      phone: '(212) 234-0783',
    },
    {
      id: 3,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Sarah Connor',
      profession: 'Bystander for Patient',
      address: '123 Main St, San Francisco, CA, 94105',
      phone: '(415) 987-6543',
    },
    {
      id: 4,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Michael Scott',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-0000',
    },
    {
      id: 5,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Dwight Schrute',
      profession: 'Errand Runner',
      address: '1855 Beet Farm Rd, Scranton, PA, 18505',
      phone: '(570) 555-5555',
    },
    {
      id: 6,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Pam Beesly',
      profession: 'Bystander for Elderly',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-1212',
    },
    {
      id: 7,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Jim Halpert',
      profession: 'Driver',
      address: '456 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-1234',
    },
    {
      id: 8,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Kelly Kapoor',
      profession: 'Errand Runner',
      address: '789 Fashion Ave, New York, NY, 10001',
      phone: '(212) 555-7890',
    },
    {
      id: 9,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Ryan Howard',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-6789',
    },
    {
      id: 10,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Stanley Hudson',
      profession: 'Bystander for Patient',
      address: '500 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-2345',
    },
    {
      id: 11,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Angela Martin',
      profession: 'Errand Runner',
      address: '1855 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-9876',
    },
    {
      id: 12,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Oscar Martinez',
      profession: 'Driver',
      address: '500 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-3456',
    },
    {
      id: 1,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Johnathan Doe',
      profession: 'Driver',
      address: '795 Folsom Ave, NY, 10003',
      phone: '(123) 456-7890',
    },
    {
      id: 2,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'George Johnson',
      profession: 'Errand Runner',
      address: '36 W 138th St,  NY, 10037',
      phone: '(212) 234-0783',
    },
    {
      id: 3,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Sarah Connor',
      profession: 'Bystander for Patient',
      address: '123 Main St, San Francisco, CA, 94105',
      phone: '(415) 987-6543',
    },
    {
      id: 4,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Michael Scott',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-0000',
    },
    {
      id: 5,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Dwight Schrute',
      profession: 'Errand Runner',
      address: '1855 Beet Farm Rd, Scranton, PA, 18505',
      phone: '(570) 555-5555',
    },
    {
      id: 6,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Pam Beesly',
      profession: 'Bystander for Elderly',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-1212',
    },
    {
      id: 7,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Jim Halpert',
      profession: 'Driver',
      address: '456 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-1234',
    },
    {
      id: 8,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Kelly Kapoor',
      profession: 'Errand Runner',
      address: '789 Fashion Ave, New York, NY, 10001',
      phone: '(212) 555-7890',
    },
    {
      id: 9,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Ryan Howard',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-6789',
    },
    {
      id: 10,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Stanley Hudson',
      profession: 'Bystander for Patient',
      address: '500 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-2345',
    },
    {
      id: 11,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Angela Martin',
      profession: 'Errand Runner',
      address: '1855 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-9876',
    },
    {
      id: 12,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Oscar Martinez',
      profession: 'Driver',
      address: '500 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-3456',
    },
    {
      id: 1,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Johnathan Doe',
      profession: 'Driver',
      address: '795 Folsom Ave, NY, 10003',
      phone: '(123) 456-7890',
    },
    {
      id: 2,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'George Johnson',
      profession: 'Errand Runner',
      address: '36 W 138th St,  NY, 10037',
      phone: '(212) 234-0783',
    },
    {
      id: 3,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Sarah Connor',
      profession: 'Bystander for Patient',
      address: '123 Main St, San Francisco, CA, 94105',
      phone: '(415) 987-6543',
    },
    {
      id: 4,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Michael Scott',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-0000',
    },
    {
      id: 5,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Dwight Schrute',
      profession: 'Errand Runner',
      address: '1855 Beet Farm Rd, Scranton, PA, 18505',
      phone: '(570) 555-5555',
    },
    {
      id: 6,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Pam Beesly',
      profession: 'Bystander for Elderly',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-1212',
    },
    {
      id: 7,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Jim Halpert',
      profession: 'Driver',
      address: '456 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-1234',
    },
    {
      id: 8,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Kelly Kapoor',
      profession: 'Errand Runner',
      address: '789 Fashion Ave, New York, NY, 10001',
      phone: '(212) 555-7890',
    },
    {
      id: 9,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Ryan Howard',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-6789',
    },
    {
      id: 10,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Stanley Hudson',
      profession: 'Bystander for Patient',
      address: '500 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-2345',
    },
    {
      id: 11,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Angela Martin',
      profession: 'Errand Runner',
      address: '1855 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-9876',
    },
    {
      id: 12,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Oscar Martinez',
      profession: 'Driver',
      address: '500 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-3456',
    },
    {
      id: 1,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Johnathan Doe',
      profession: 'Driver',
      address: '795 Folsom Ave, NY, 10003',
      phone: '(123) 456-7890',
    },
    {
      id: 2,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'George Johnson',
      profession: 'Errand Runner',
      address: '36 W 138th St,  NY, 10037',
      phone: '(212) 234-0783',
    },
    {
      id: 3,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Sarah Connor',
      profession: 'Bystander for Patient',
      address: '123 Main St, San Francisco, CA, 94105',
      phone: '(415) 987-6543',
    },
    {
      id: 4,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Michael Scott',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-0000',
    },
    {
      id: 5,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Dwight Schrute',
      profession: 'Errand Runner',
      address: '1855 Beet Farm Rd, Scranton, PA, 18505',
      phone: '(570) 555-5555',
    },
    {
      id: 6,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Pam Beesly',
      profession: 'Bystander for Elderly',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-1212',
    },
    {
      id: 7,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Jim Halpert',
      profession: 'Driver',
      address: '456 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-1234',
    },
    {
      id: 8,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Kelly Kapoor',
      profession: 'Errand Runner',
      address: '789 Fashion Ave, New York, NY, 10001',
      phone: '(212) 555-7890',
    },
    {
      id: 9,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Ryan Howard',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-6789',
    },
    {
      id: 10,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Stanley Hudson',
      profession: 'Bystander for Patient',
      address: '500 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-2345',
    },
    {
      id: 11,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Angela Martin',
      profession: 'Errand Runner',
      address: '1855 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-9876',
    },
    {
      id: 12,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Oscar Martinez',
      profession: 'Driver',
      address: '500 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-3456',
    },
    {
      id: 1,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Johnathan Doe',
      profession: 'Driver',
      address: '795 Folsom Ave, NY, 10003',
      phone: '(123) 456-7890',
    },
    {
      id: 2,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'George Johnson',
      profession: 'Errand Runner',
      address: '36 W 138th St,  NY, 10037',
      phone: '(212) 234-0783',
    },
    {
      id: 3,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Sarah Connor',
      profession: 'Bystander for Patient',
      address: '123 Main St, San Francisco, CA, 94105',
      phone: '(415) 987-6543',
    },
    {
      id: 4,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Michael Scott',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-0000',
    },
    {
      id: 5,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Dwight Schrute',
      profession: 'Errand Runner',
      address: '1855 Beet Farm Rd, Scranton, PA, 18505',
      phone: '(570) 555-5555',
    },
    {
      id: 6,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Pam Beesly',
      profession: 'Bystander for Elderly',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-1212',
    },
    {
      id: 7,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Jim Halpert',
      profession: 'Driver',
      address: '456 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-1234',
    },
    {
      id: 8,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Kelly Kapoor',
      profession: 'Errand Runner',
      address: '789 Fashion Ave, New York, NY, 10001',
      phone: '(212) 555-7890',
    },
    {
      id: 9,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Ryan Howard',
      profession: 'Driver',
      address: '1725 Slough Ave, Scranton, PA, 18505',
      phone: '(570) 555-6789',
    },
    {
      id: 10,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Stanley Hudson',
      profession: 'Bystander for Patient',
      address: '500 Paper St, Scranton, PA, 18505',
      phone: '(570) 555-2345',
    },
    {
      id: 11,
      imgSrc: 'assets/images/profile/user-2.jpg',
      name: 'Angela Martin',
      profession: 'Errand Runner',
      address: '1855 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-9876',
    },
    {
      id: 12,
      imgSrc: 'assets/images/profile/user-4.jpg',
      name: 'Oscar Martinez',
      profession: 'Driver',
      address: '500 Accountant St, Scranton, PA, 18505',
      phone: '(570) 555-3456',
    },
  ];


  public filteredCards = this.userCards; // Array for filtered results

  // Function to filter user cards based on the search term
  applyFilter(event: KeyboardEvent) {
    const searchTerm = (event.target as HTMLInputElement).value.toLowerCase();

    this.filteredCards = this.userCards.filter(userCard =>
      userCard.name.toLowerCase().includes(searchTerm) ||
      userCard.profession.toLowerCase().includes(searchTerm) ||
      userCard.address.toLowerCase().includes(searchTerm)
    );
  }
}
